### PR TITLE
fix: respect HTTP proxy settings

### PR DESCRIPTION
**Pull request by smira**
This should correctly apply `HTTP_PROXY` settings when set via the build
args.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
required patch for containing repo:

```diff
diff --git a/Makefile b/Makefile
index a4588c3..b567da2 100644
--- a/Makefile
+++ b/Makefile
@@ -12,6 +12,8 @@ PUSH ?= false
 COMMON_ARGS := --file=Pkgfile
 COMMON_ARGS += --progress=$(PROGRESS)
 COMMON_ARGS += --platform=$(PLATFORM)
+COMMON_ARGS += --build-arg=http_proxy=$(http_proxy)
+COMMON_ARGS += --build-arg=https_proxy=$(https_proxy)
 
 , := ,
 empty :=
```

**Comment by smira** [comment]
Fix got validated in the proxy-only environment

**Review by Unix4ever — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
